services:
  backend:
    build:
      context: ./symfony-back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./symfony-back:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://user:password@db:3306/exam_management
    depends_on:
      - db

  frontend:
    build: ./angular-front
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./angular-front:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam_management
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
